# Generated by Django 6.0.7 on 2026-07-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelisting',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('INR', 'INR (₹)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)')], default='USD', max_length=3),
        ),
    ]
